### ISSUE TITLE
A few errors in my queue

### ISSUE THREAD

**Issue by owcz** [toollabs/video2commons#21]
Restarting doesn't work—not sure how to handle these:
1. `An exception occured: TaskError: pywikibot.Error: APIError: stashfailed: The file is a corrupt or otherwise unreadable ZIP file. It cannot be properly checked for security. [help:See https://commons.wikimedia.org/w/api.php for API usage; offset:121634816]`
2. `An exception occured: TaskError: pywikibot.Error: APIError: stashedfilenotfound: Could not find the file in the stash: key '13zkzr0v7uw4.qxfqvn.1803702.webm' not found in stash [help:See https://commons.wikimedia.org/w/api.php for API usage]`
3. `An exception occured: TaskError: pywikibot.Error: APIError: stashfailed: Invalid chunk offset [help:See https://commons.wikimedia.org/w/api.php for API usage; offset:913798300]`

**Comment by zhuyifei1999** [comment]
First is [T33930: Image upload fail with error bad-zip due to being misdetected as a broken zip irrespective of mimetype](https://phabricator.wikimedia.org/T33930)

Second and third are consequences of [T128358: Uploading 1.2GB ogv results in 503](https://phabricator.wikimedia.org/T128358), workaround in [T129216: Pywikibot should support async chunked uploading](https://phabricator.wikimedia.org/T129216.)

**Comment by zhuyifei1999** [comment]
Not fixable in this tool

**Comment by owcz** [comment]
Can you clarify (especially re: issue 3 above)? These aren't fixable? It would be helpful to have the error notice fail gracefully, perhaps with a link of how else to upload the video, perhaps with videoconvert or something

**Comment by zhuyifei1999** [comment]
There's no way in this tool that's able workaround this issue.

The bad-zip error cannot be overridden with any uploading methods (unless the file is again transcoded with different parameters, on a case by case basis)
The stash errors must be fixed in either Wikimedia backend, or workarounded in pywikibot

**Comment by zhuyifei1999** [comment]
Oh AFAIK videoconvert don't use async chunked uploading either, so it won't be able to upload the files that failed with stash errors. Only uploading with UW or rillke's bigChunkedUploading.js can help.

**Comment by owcz** [comment]
I was able to take the bad-zip file to the videoconvert tool. Perhaps it re-encoded it—not sure—but it uploaded just fine. If I recall correctly, bigChunkedUploading choked on the zip error too.

**Comment by zhuyifei1999** [comment]
Re videoconvert on bad-zip errors: yes, videoconvert unconditionally re-encodes uploaded media, IIRC.
