### ISSUE TITLE
Video resolution category

### ISSUE THREAD

**Issue by owcz** [toollabs/video2commons#77]
Can the tool autotag the right video resolution category? https://commons.wikimedia.org/wiki/Category:Videos_by_display_resolution

Would save a patroller some work

**Comment by zhuyifei1999** [comment]
The categorization (file description generation) happens on the frontend, but the frontend has no idea about the resolution until the backend downloads the video.

Is it fine if the generated file description contains `[[Category:Video display resolution 0 x 0‎]]` and the backend replaces it with the actual resolution? Otherwise it's probably technically impossible.

**Comment by owcz** [comment]
I think it's fine as long as it's automated. Perhaps a different container category would be appropriate, and then it can move to the right cat when the backend does its thing

**Comment by zhuyifei1999** [comment]
I'm still not perfectly comfortable with these categories:

* What's the point of these categories? We don't have categories like `Category:Image resolution 1024 x 768` or `Category:20-page document`. FWIW, there was a discussion [Revent's talk page](https://commons.wikimedia.org/w/index.php?title=User_talk:Revent&oldid=231006416#Category:Video_display_resolution_640_x_360.2C_etc.)
* I don't like automating the addition of extra meta categories during the description generation (except `Uploaded with video2commons`) for one specific tool. If it really should be implemented, use a bot to apply to all eligible files (in this case videos).
* The only possible implementation I can think of is highly hacky:
  * Will make the already hacky backend even more hacky. i.e. We current have no module modifying the file description conditionally depending on the file itself (the only place that modifies the file description is during server-side upload preparation, in which `[[Category:Uploaded with video2commons]]` is replaced with `[[Category:Uploaded with video2commons/Server-side uploads]]`). FFprobe for file information is only implemented in the transcoding module, and it's logically incorrect to modify the description there.
  * Counter-intuitive: There would be no indication that the tool would change `[[Category:Video display resolution 0 x 0‎]]`, and actually unconsciously ask the user to fix that category manually.
  * #49 would be not-fixable (or much more difficult to work with) due to an existing broken category.

So I guess I'll close this as a WONTFIX. If this needs to be implemented, either use a bot or make MediaWiki core / extension do this.
